//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MinsurRepoEntities : DbContext
    {
        public MinsurRepoEntities()
            : base("name=MinsurRepoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MS_ADSORCION> MS_ADSORCION { get; set; }
        public virtual DbSet<MS_CHANCADORA> MS_CHANCADORA { get; set; }
        public virtual DbSet<MS_CONSUMO_COMBUSTIBLE> MS_CONSUMO_COMBUSTIBLE { get; set; }
        public virtual DbSet<MS_DESORCION> MS_DESORCION { get; set; }
        public virtual DbSet<MS_ESTADO> MS_ESTADO { get; set; }
        public virtual DbSet<MS_GUARDIA> MS_GUARDIA { get; set; }
        public virtual DbSet<MS_LISTA> MS_LISTA { get; set; }
        public virtual DbSet<MS_LISTA_VALOR> MS_LISTA_VALOR { get; set; }
        public virtual DbSet<MS_MANT_EQUIPOS> MS_MANT_EQUIPOS { get; set; }
        public virtual DbSet<MS_MANT_PRODUCCION_X_HORA> MS_MANT_PRODUCCION_X_HORA { get; set; }
        public virtual DbSet<MS_PARADA> MS_PARADA { get; set; }
        public virtual DbSet<MS_PARAMETRO> MS_PARAMETRO { get; set; }
        public virtual DbSet<MS_PROCESO> MS_PROCESO { get; set; }
        public virtual DbSet<MS_TIPO_PARADA> MS_TIPO_PARADA { get; set; }
        public virtual DbSet<MS_INGRESONIVELESPOZA> MS_INGRESONIVELESPOZA { get; set; }
        public virtual DbSet<MS_INGRESOPORGOTEO> MS_INGRESOPORGOTEO { get; set; }
        public virtual DbSet<MS_AGUAS_OPERACIONES> MS_AGUAS_OPERACIONES { get; set; }
        public virtual DbSet<MS_APILAMIENTO> MS_APILAMIENTO { get; set; }
        public virtual DbSet<MS_CAMIONES> MS_CAMIONES { get; set; }
        public virtual DbSet<MS_FLUJOS_PRESIONES> MS_FLUJOS_PRESIONES { get; set; }
        public virtual DbSet<MS_OPCION> MS_OPCION { get; set; }
        public virtual DbSet<MS_ROL> MS_ROL { get; set; }
        public virtual DbSet<MS_ROL_OPCION> MS_ROL_OPCION { get; set; }
        public virtual DbSet<MS_USUARIO> MS_USUARIO { get; set; }
        public virtual DbSet<MS_USUARIO_ROL> MS_USUARIO_ROL { get; set; }
        public virtual DbSet<MS_TURNO_LIX> MS_TURNO_LIX { get; set; }
        public virtual DbSet<MS_CONTROL_DIG_LIXIVIACION> MS_CONTROL_DIG_LIXIVIACION { get; set; }
        public virtual DbSet<MS_PROD_CHANCADORA> MS_PROD_CHANCADORA { get; set; }
        public virtual DbSet<MS_PROD_ORE_BIN> MS_PROD_ORE_BIN { get; set; }
        public virtual DbSet<MS_PRODUCCION> MS_PRODUCCION { get; set; }
    }
}
