//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_AGUAS_OPERACIONES
    {
        public int agua_op_id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> turno_id { get; set; }
        public Nullable<int> tecnico_id { get; set; }
        public Nullable<double> nivel_tk_1 { get; set; }
        public Nullable<double> nivel_tk_2 { get; set; }
        public Nullable<double> nivel_tk_contraincendio { get; set; }
        public Nullable<double> nivel_tk_chancado { get; set; }
        public Nullable<double> nivel_pm_pad { get; set; }
        public Nullable<double> nivel_pm_pls { get; set; }
        public Nullable<double> nivel_tk_botadero { get; set; }
        public Nullable<double> consumo_mina_cat_777 { get; set; }
        public Nullable<double> consumo_mina_riego_vias { get; set; }
        public Nullable<double> consumo_mina_riego_caliza { get; set; }
        public Nullable<double> consumo_geologia { get; set; }
        public Nullable<double> consumo_exploracion { get; set; }
        public Nullable<double> consumo_proy_campamento { get; set; }
        public Nullable<double> consumo_proy_obras { get; set; }
        public Nullable<double> consumo_rrhh_timpure { get; set; }
        public Nullable<double> consumo_rrhh_pucamara { get; set; }
        public Nullable<double> pluviometro_lixiviacion { get; set; }
        public Nullable<double> pluviometro_planta_adr { get; set; }
        public Nullable<double> pluviomento_pozos_agua { get; set; }
        public Nullable<double> bombeo_chancado_niv_inicial { get; set; }
        public Nullable<double> bombeo_chancado_niv_final { get; set; }
        public Nullable<double> totalizador_pozo_1 { get; set; }
        public Nullable<double> totalizador_pozo_2 { get; set; }
        public Nullable<double> totalizador_pozo_3 { get; set; }
        public Nullable<double> totalizador_pozo_4 { get; set; }
        public Nullable<double> totalizador_pozo_5 { get; set; }
        public Nullable<double> totalizador_pozo_6 { get; set; }
        public Nullable<double> totalizador_ingreso_tk_2 { get; set; }
        public Nullable<double> totalizador_make_up_planta { get; set; }
        public Nullable<double> nivel_freatico_pozo_1 { get; set; }
        public Nullable<double> nivel_freatico_pozo_2 { get; set; }
        public Nullable<double> nivel_freatico_pozo_3 { get; set; }
        public Nullable<double> nivel_freatico_pozo_4 { get; set; }
        public Nullable<double> nivel_freatico_pozo_5 { get; set; }
        public Nullable<double> nivel_freatico_pozo_6 { get; set; }
        public Nullable<double> variador_velocidad_pozo_1 { get; set; }
        public Nullable<double> variador_velocidad_pozo_2 { get; set; }
        public Nullable<double> variador_velocidad_pozo_3 { get; set; }
        public Nullable<double> variador_velocidad_pozo_4 { get; set; }
        public Nullable<double> variador_velocidad_pozo_5 { get; set; }
        public Nullable<double> variador_velocidad_pozo_6 { get; set; }
        public Nullable<bool> activo { get; set; }
        public string usuario_crea { get; set; }
        public Nullable<System.DateTime> fecha_crea { get; set; }
        public string usuario_mod { get; set; }
        public Nullable<System.DateTime> fecha_mod { get; set; }
    }
}
