//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_CONTROL_DIG_LIXIVIACION
    {
        public int control_dig_lix_id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> turno_id { get; set; }
        public Nullable<int> celda_id { get; set; }
        public Nullable<int> tecnico_lixiviacion_id { get; set; }
        public Nullable<int> tecnico_apilamiento_id { get; set; }
        public Nullable<int> nro_viajes { get; set; }
        public string celda_opc { get; set; }
        public Nullable<int> nro_camiones { get; set; }
        public Nullable<double> ley_mineral { get; set; }
        public Nullable<double> poligono { get; set; }
        public Nullable<double> pluviometro { get; set; }
        public Nullable<double> cal_viva { get; set; }
        public Nullable<double> cal_hidratada { get; set; }
        public Nullable<double> corte { get; set; }
        public Nullable<double> ripeo { get; set; }
        public Nullable<double> totalizador_tk_2 { get; set; }
        public Nullable<double> nivel_tk_2 { get; set; }
        public Nullable<double> presion_flujo { get; set; }
        public string comentarios { get; set; }
        public Nullable<double> flujo { get; set; }
        public Nullable<double> presion_adr { get; set; }
        public Nullable<double> presion_sump { get; set; }
        public Nullable<double> presion_925 { get; set; }
        public Nullable<bool> activo { get; set; }
        public string usuario_crea { get; set; }
        public Nullable<System.DateTime> fecha_crea { get; set; }
        public string usuario_mod { get; set; }
        public Nullable<System.DateTime> fecha_mod { get; set; }
    }
}
