//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_DESORCION
    {
        public int desorcion_id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string num_fundicion { get; set; }
        public string mes { get; set; }
        public Nullable<int> num_desorcion { get; set; }
        public Nullable<int> num_desorcion_mes { get; set; }
        public Nullable<int> num_col_desc { get; set; }
        public Nullable<double> peso_col_desc { get; set; }
        public string hora_inicio { get; set; }
        public string hora_fin { get; set; }
        public Nullable<double> au_rico { get; set; }
        public Nullable<double> au_pobre { get; set; }
        public Nullable<double> ag_rico { get; set; }
        public Nullable<double> ag_pobre { get; set; }
        public Nullable<double> hg_rico { get; set; }
        public Nullable<double> hg_pobre { get; set; }
        public Nullable<bool> activo { get; set; }
        public string usuario_crea { get; set; }
        public Nullable<System.DateTime> fecha_crea { get; set; }
        public string usuario_mod { get; set; }
        public Nullable<System.DateTime> fecha_mod { get; set; }
    }
}
