//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_FLUJOS_PRESIONES
    {
        public int flujo_presion_id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> celda_id { get; set; }
        public Nullable<int> operador_id { get; set; }
        public Nullable<int> ingeniero_id { get; set; }
        public Nullable<double> flujo { get; set; }
        public Nullable<double> presion { get; set; }
        public Nullable<double> flujo_real { get; set; }
        public Nullable<double> presion_real { get; set; }
        public Nullable<double> flujo_corregido { get; set; }
        public Nullable<double> presion_corregida { get; set; }
        public Nullable<double> totalizador { get; set; }
        public string comentarios { get; set; }
        public Nullable<bool> activo { get; set; }
        public string usuario_crea { get; set; }
        public Nullable<System.DateTime> fecha_crea { get; set; }
        public string usuario_mod { get; set; }
        public Nullable<System.DateTime> fecha_mod { get; set; }
    }
}
