//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_INGRESOPORGOTEO
    {
        public long ingresoporgoteo_id { get; set; }
        public string codArea { get; set; }
        public Nullable<int> flujo { get; set; }
        public Nullable<decimal> tonelajeChancado { get; set; }
        public Nullable<decimal> leyAuChancado { get; set; }
        public Nullable<decimal> leyAgChancado { get; set; }
        public Nullable<decimal> Tonelaje_Overliner_ { get; set; }
        public Nullable<decimal> leyAuOverliner { get; set; }
        public Nullable<decimal> leyAgOverliner { get; set; }
        public Nullable<System.DateTime> fechaInicioApilamiento { get; set; }
        public Nullable<System.DateTime> fechaFinApilamiento { get; set; }
        public Nullable<System.DateTime> fechaInicioRiego { get; set; }
        public Nullable<System.DateTime> fechaFinRiego { get; set; }
        public Nullable<System.DateTime> fechaFinRealRiego { get; set; }
        public Nullable<int> diaRiegoAlaFecha { get; set; }
        public Nullable<int> diaPrograRiego { get; set; }
        public Nullable<decimal> onzasAu { get; set; }
        public Nullable<decimal> onzasAg { get; set; }
        public Nullable<decimal> TMS { get; set; }
        public Nullable<int> celdaId { get; set; }
        public Nullable<bool> activo { get; set; }
        public string usuario_crea { get; set; }
        public Nullable<System.DateTime> fecha_crea { get; set; }
        public string usuario_mod { get; set; }
        public Nullable<System.DateTime> fecha_mod { get; set; }
    }
}
