//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_MANT_EQUIPOS
    {
        public int equipo_id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> guardia_id { get; set; }
        public Nullable<int> turno_id { get; set; }
        public string camiom_cargador { get; set; }
        public Nullable<int> tipo_actividad_id { get; set; }
        public Nullable<int> operador_id { get; set; }
        public string hora_inicial { get; set; }
        public string hora_fin { get; set; }
        public Nullable<double> tancada { get; set; }
        public string hora_ini_mant { get; set; }
        public string hora_fin_mant { get; set; }
        public string comentarios { get; set; }
        public Nullable<int> equipo_cargio_id { get; set; }
        public Nullable<int> material_id { get; set; }
        public Nullable<int> zona_carguio { get; set; }
        public Nullable<int> punto_descarga { get; set; }
        public Nullable<int> numero_viajes { get; set; }
        public Nullable<double> produccion_total { get; set; }
        public Nullable<bool> activo { get; set; }
        public string usuario_crea { get; set; }
        public Nullable<System.DateTime> fecha_crea { get; set; }
        public string usuario_mod { get; set; }
        public Nullable<System.DateTime> fecha_mod { get; set; }
    }
}
