//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_MANT_PRODUCCION_X_HORA
    {
        public int produccion_hora_id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> guardia_id { get; set; }
        public Nullable<int> turno_id { get; set; }
        public string hora { get; set; }
        public string camion { get; set; }
        public Nullable<double> toneladas { get; set; }
        public Nullable<int> viajes { get; set; }
        public Nullable<int> material_id { get; set; }
        public Nullable<int> ruta_id { get; set; }
        public Nullable<double> tancada { get; set; }
        public Nullable<int> zona_cargio_id { get; set; }
        public Nullable<int> equipo_cargio_id { get; set; }
        public Nullable<double> ton1 { get; set; }
        public Nullable<double> ton2 { get; set; }
        public Nullable<double> ton3 { get; set; }
        public Nullable<double> ton4 { get; set; }
        public Nullable<double> ton5 { get; set; }
        public Nullable<double> ton6 { get; set; }
        public Nullable<double> ton7 { get; set; }
        public Nullable<double> ton8 { get; set; }
        public Nullable<double> ton9 { get; set; }
        public Nullable<double> ton10 { get; set; }
        public Nullable<double> ton11 { get; set; }
        public Nullable<double> ton12 { get; set; }
        public Nullable<double> ton13 { get; set; }
        public Nullable<double> ton14 { get; set; }
        public Nullable<double> ton15 { get; set; }
        public Nullable<double> ton16 { get; set; }
        public Nullable<double> ton17 { get; set; }
        public Nullable<double> ton18 { get; set; }
        public Nullable<double> ton19 { get; set; }
        public Nullable<double> ton20 { get; set; }
        public Nullable<double> ton21 { get; set; }
        public Nullable<double> ton22 { get; set; }
        public Nullable<double> ton23 { get; set; }
        public Nullable<double> ton24 { get; set; }
        public Nullable<double> ton25 { get; set; }
        public Nullable<double> ton26 { get; set; }
        public Nullable<double> ton27 { get; set; }
        public Nullable<double> ton28 { get; set; }
        public Nullable<double> ton29 { get; set; }
        public Nullable<double> ton30 { get; set; }
        public Nullable<bool> activo { get; set; }
        public string usuario_crea { get; set; }
        public Nullable<System.DateTime> fecha_crea { get; set; }
        public string usuario_mod { get; set; }
        public Nullable<System.DateTime> fecha_mod { get; set; }
    }
}
