//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_PROCESO
    {
        public int proceso_id { get; set; }
        public string codigo { get; set; }
        public string anho { get; set; }
        public string mes { get; set; }
        public System.DateTime mcl_fecha_inicio { get; set; }
        public System.DateTime mcl_fecha_fin { get; set; }
        public System.DateTime adr_fecha_inicio { get; set; }
        public System.DateTime adr_fecha_fin { get; set; }
        public Nullable<bool> activo { get; set; }
        public string usuario_crea { get; set; }
        public Nullable<System.DateTime> fecha_crea { get; set; }
        public string usuario_mod { get; set; }
        public Nullable<System.DateTime> fecha_mod { get; set; }
    }
}
