//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_TIPO_PARADA
    {
        public int tipo_parada_id { get; set; }
        public int tipo_parada { get; set; }
        public int sub_tipo_parada { get; set; }
        public string codigo_serie { get; set; }
        public string descripcion_serie { get; set; }
        public Nullable<int> estado_serie { get; set; }
        public string observaciones { get; set; }
        public Nullable<bool> activo { get; set; }
        public string usuario_crea { get; set; }
        public Nullable<System.DateTime> fecha_crea { get; set; }
        public string usuario_mod { get; set; }
        public Nullable<System.DateTime> fecha_mod { get; set; }
    }
}
