//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_TURNO_LIX
    {
        public int turno_lix_id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> turno_id { get; set; }
        public Nullable<double> poza_pls { get; set; }
        public Nullable<double> lluvia { get; set; }
        public Nullable<double> ley_oro_m1_tren_1 { get; set; }
        public Nullable<double> ley_oro_m1_tren_2 { get; set; }
        public Nullable<double> ley_oro_m2_tren_1 { get; set; }
        public Nullable<double> ley_oro_m2_tren_2 { get; set; }
        public Nullable<double> ley_oro_m3 { get; set; }
        public Nullable<double> ley_plata_m1_tren_1 { get; set; }
        public Nullable<double> ley_plata_m1_tren_2 { get; set; }
        public Nullable<double> ley_plata_m2_tren_1 { get; set; }
        public Nullable<double> ley_plata_m2_tren_2 { get; set; }
        public Nullable<double> flujo_adr_tren_1 { get; set; }
        public Nullable<double> flujo_adr_tren_2 { get; set; }
        public Nullable<double> flujo_lixiviacion { get; set; }
        public Nullable<double> factor { get; set; }
        public Nullable<double> flujo_adr_tren_1_calc { get; set; }
        public Nullable<double> flujo_adr_tren_2_calc { get; set; }
        public Nullable<double> flujo_lixiviacion_calc { get; set; }
        public Nullable<bool> activo { get; set; }
        public string usuario_crea { get; set; }
        public Nullable<System.DateTime> fecha_crea { get; set; }
        public string usuario_mod { get; set; }
        public Nullable<System.DateTime> fecha_mod { get; set; }
    }
}
